version: '3.9'
services:
  client:
    container_name: client-dev-app
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000